import JSZip from "jszip";
import type { Page, Project } from "@/types";
import { renderPuckToHtml } from "./render-html";
import {
  organizationSchema,
  articleSchema,
  faqSchema,
} from "@/lib/seo/schema-generator";
import {
  buildRobotsTxt,
  buildSitemapXml,
  buildSitemapEntriesFromPages,
  DEFAULT_ROBOTS_CONFIG,
} from "@/lib/seo/robots-sitemap";

/**
 * Package all pages of a project into a ready-to-run Next.js 16 scaffold (ZIP).
 * Lightweight approach: we pre-render each page to static HTML and serve via
 * `app/[...slug]/page.tsx` returning `dangerouslySetInnerHTML`. The archive
 * contains exactly what's needed to `npm install && npm run dev`.
 */
import type { LocalBusinessSettings } from "@/lib/stores/settings-store";

export async function buildNextJsZip(opts: {
  projectName: string;
  pages: Page[];
  project?: Project;
  localBusiness?: LocalBusinessSettings;
}): Promise<Buffer> {
  const zip = new JSZip();
  const root = sanitizeDir(opts.projectName);
  const f = zip.folder(root)!;

  f.file("package.json", packageJson(root));
  f.file("tsconfig.json", tsconfig);
  f.file("next.config.ts", nextConfig);
  f.file("README.md", readme(opts.projectName, opts.pages));
  f.file(".gitignore", gitignore);

  const app = f.folder("app")!;
  app.file("layout.tsx", layoutTsx);
  app.file("globals.css", globalsCss);

  // SEO: robots.txt + sitemap.xml at the project root
  if (opts.project) {
    const baseUrl = `https://${opts.project.domain}`;
    f.file("public/robots.txt", buildRobotsTxt(DEFAULT_ROBOTS_CONFIG, baseUrl));
    const entries = buildSitemapEntriesFromPages(opts.project, opts.pages);
    f.file("public/sitemap.xml", buildSitemapXml(entries));
  }

  // Homepage (either the page with slug "/" or the first one)
  const home =
    opts.pages.find((p) => p.slug === "/" || p.slug === "home") ??
    opts.pages[0];
  if (home) {
    app.file("page.tsx", staticPageTsx(home, opts.project, opts.localBusiness));
  }

  // Other pages under /[slug]/page.tsx
  for (const page of opts.pages) {
    if (page === home) continue;
    const slug = page.slug.replace(/^\//, "") || page.id;
    app
      .folder(slug)!
      .file("page.tsx", staticPageTsx(page, opts.project, opts.localBusiness));
  }

  return Buffer.from(await zip.generateAsync({ type: "nodebuffer" }));
}

function sanitizeDir(s: string) {
  return (
    s
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-|-$/g, "") || "rezen-site"
  );
}

function staticPageTsx(
  page: Page,
  project?: Project,
  localBusiness?: LocalBusinessSettings,
): string {
  const html = renderPuckToHtml(page.puckData, {
    title: page.title,
    page,
    project,
    localBusiness,
  });
  const body = html.substring(html.indexOf("<body>") + 6, html.indexOf("</body>"));
  const styleTag = html.match(/<style[^>]*>([\s\S]*?)<\/style>/);
  const css = styleTag?.[1] ?? "";

  // Build JSON-LD payloads for embedding via next/script (proper SSR-safe)
  const schemas: Record<string, unknown>[] = [];
  if (project) {
    schemas.push(organizationSchema(project));
    schemas.push(articleSchema(project, page));
  }
  // FAQ auto-detect from puck content
  const faqItems: { question: string; answer: string }[] = [];
  for (const item of page.puckData.content ?? []) {
    if (item.type === "FAQ") {
      const items = (item.props as Record<string, unknown>).items as
        | Array<{ question: string; answer: string }>
        | undefined;
      if (Array.isArray(items)) faqItems.push(...items.filter((it) => it.question && it.answer));
    }
  }
  if (faqItems.length > 0) schemas.push(faqSchema(faqItems));

  const schemaScripts = schemas
    .map(
      (s, i) =>
        `      <script type="application/ld+json" key="${i}" dangerouslySetInnerHTML={{ __html: ${JSON.stringify(JSON.stringify(s))} }} />`,
    )
    .join("\n");

  return `// Auto-generated by REZEN Sites export
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: ${JSON.stringify(page.seo.metaTitle || page.title)},
  description: ${JSON.stringify(page.seo.metaDescription || "")},
  alternates: {
    canonical: ${JSON.stringify(page.seo.canonicalUrl || "")},
  },
  openGraph: {
    title: ${JSON.stringify(page.seo.og.title ?? page.seo.metaTitle ?? page.title)},
    description: ${JSON.stringify(page.seo.og.description ?? page.seo.metaDescription ?? "")},
    ${page.seo.og.image ? `images: [${JSON.stringify(page.seo.og.image)}],` : ""}
  },
  robots: ${page.seo.indexable ? `"index,follow"` : `"noindex,nofollow"`},
};

export default function Page() {
  return (
    <>
${schemaScripts}
      <style dangerouslySetInnerHTML={{ __html: ${JSON.stringify(css)} }} />
      <div dangerouslySetInnerHTML={{ __html: ${JSON.stringify(body)} }} />
    </>
  );
}
`;
}

function packageJson(name: string) {
  return JSON.stringify(
    {
      name,
      version: "0.1.0",
      private: true,
      scripts: {
        dev: "next dev",
        build: "next build",
        start: "next start",
      },
      dependencies: {
        next: "16.2.4",
        react: "19.2.4",
        "react-dom": "19.2.4",
      },
      devDependencies: {
        "@types/node": "^20",
        "@types/react": "^19",
        "@types/react-dom": "^19",
        typescript: "^5",
      },
    },
    null,
    2,
  );
}

const tsconfig = `{
  "compilerOptions": {
    "target": "ES2022",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": false,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [{ "name": "next" }],
    "paths": { "@/*": ["./*"] }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
`;

const nextConfig = `import type { NextConfig } from "next";
const nextConfig: NextConfig = {};
export default nextConfig;
`;

const layoutTsx = `import type { ReactNode } from "react";
import "./globals.css";

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="it">
      <body>{children}</body>
    </html>
  );
}
`;

const globalsCss = `html, body { margin: 0; padding: 0; }
body { background: #12121d; color: #f3f2f0; font-family: -apple-system, BlinkMacSystemFont, 'Inter', sans-serif; }
`;

const gitignore = `node_modules
.next
.env
.env.local
*.log
.DS_Store
`;

function readme(name: string, pages: Page[]) {
  return `# ${name}

Static export from REZEN Sites (VerumFlow).

## Quick start

\`\`\`bash
npm install
npm run dev
\`\`\`

## Pages

${pages.map((p) => `- \`${p.slug}\` — ${p.title}`).join("\n")}

Each page renders server-side from pre-baked HTML. To switch to interactive Puck rendering,
replace \`app/**/page.tsx\` with \`<Render config={puckConfig} data={data} />\` and copy
your \`lib/puck/config.ts\` + \`lib/puck/components.tsx\` into this scaffold.
`;
}
