import type { PuckData } from "@/types";

/**
 * Export a single page as a standalone React component (.tsx).
 * The output imports the local `puck-components.tsx` and renders the puckData via Puck's `<Render>`.
 */
export function exportReactComponent(
  data: PuckData,
  opts: { componentName: string },
): string {
  const safe = sanitizeName(opts.componentName);
  const serialized = JSON.stringify(data, null, 2);
  return `// Auto-generated by REZEN Sites (VerumFlow) — React single-file export
// Drop this into any Next.js / Vite project that already has @measured/puck
// and the Luminous component config. Adjust the import path below.

import { Render } from "@measured/puck";
import { puckConfig } from "./puck-config"; // <-- your copy of lib/puck/config.ts

const data = ${serialized} as const;

export default function ${safe}() {
  return <Render config={puckConfig} data={data as never} />;
}
`;
}

function sanitizeName(name: string) {
  const cleaned = name
    .replace(/[^a-zA-Z0-9]/g, " ")
    .trim()
    .split(/\s+/)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join("");
  return cleaned.length > 0 ? cleaned : "Page";
}
