// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/login" | "/projects" | "/projects/[projectId]" | "/projects/[projectId]/alerts" | "/projects/[projectId]/analytics" | "/projects/[projectId]/analytics/adsense" | "/projects/[projectId]/analytics/google-ads" | "/projects/[projectId]/cms" | "/projects/[projectId]/cms/[collectionId]" | "/projects/[projectId]/dashboard" | "/projects/[projectId]/forms" | "/projects/[projectId]/pages" | "/projects/[projectId]/pages/[pageId]" | "/projects/[projectId]/settings" | "/projects/[projectId]/settings/domains" | "/projects/[projectId]/settings/general" | "/projects/[projectId]/settings/redirects" | "/projects/[projectId]/settings/staging" | "/projects/[projectId]/settings/tracking" | "/projects/[projectId]/settings/versions"
type AppRouteHandlerRoutes = "/api/ai/cms-schema" | "/api/ai/edit-section" | "/api/ai/generate-page" | "/api/ai/seo-fill" | "/api/export/[format]" | "/api/import/design-zip" | "/api/import/framer-url" | "/api/import/webflow-url"
type PageRoutes = never
type LayoutRoutes = "/" | "/projects/[projectId]/settings"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/ai/cms-schema": {}
  "/api/ai/edit-section": {}
  "/api/ai/generate-page": {}
  "/api/ai/seo-fill": {}
  "/api/export/[format]": { "format": string; }
  "/api/import/design-zip": {}
  "/api/import/framer-url": {}
  "/api/import/webflow-url": {}
  "/login": {}
  "/projects": {}
  "/projects/[projectId]": { "projectId": string; }
  "/projects/[projectId]/alerts": { "projectId": string; }
  "/projects/[projectId]/analytics": { "projectId": string; }
  "/projects/[projectId]/analytics/adsense": { "projectId": string; }
  "/projects/[projectId]/analytics/google-ads": { "projectId": string; }
  "/projects/[projectId]/cms": { "projectId": string; }
  "/projects/[projectId]/cms/[collectionId]": { "projectId": string; "collectionId": string; }
  "/projects/[projectId]/dashboard": { "projectId": string; }
  "/projects/[projectId]/forms": { "projectId": string; }
  "/projects/[projectId]/pages": { "projectId": string; }
  "/projects/[projectId]/pages/[pageId]": { "projectId": string; "pageId": string; }
  "/projects/[projectId]/settings": { "projectId": string; }
  "/projects/[projectId]/settings/domains": { "projectId": string; }
  "/projects/[projectId]/settings/general": { "projectId": string; }
  "/projects/[projectId]/settings/redirects": { "projectId": string; }
  "/projects/[projectId]/settings/staging": { "projectId": string; }
  "/projects/[projectId]/settings/tracking": { "projectId": string; }
  "/projects/[projectId]/settings/versions": { "projectId": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/projects/[projectId]/settings": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
