// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../app/(app)/projects/[projectId]/alerts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/alerts">> = Specific
  const handler = {} as typeof import("../../../app/(app)/projects/[projectId]/alerts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/projects/[projectId]/analytics/adsense/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/analytics/adsense">> = Specific
  const handler = {} as typeof import("../../../app/(app)/projects/[projectId]/analytics/adsense/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/projects/[projectId]/analytics/google-ads/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/analytics/google-ads">> = Specific
  const handler = {} as typeof import("../../../app/(app)/projects/[projectId]/analytics/google-ads/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/projects/[projectId]/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/analytics">> = Specific
  const handler = {} as typeof import("../../../app/(app)/projects/[projectId]/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/projects/[projectId]/cms/[collectionId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/cms/[collectionId]">> = Specific
  const handler = {} as typeof import("../../../app/(app)/projects/[projectId]/cms/[collectionId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/projects/[projectId]/cms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/cms">> = Specific
  const handler = {} as typeof import("../../../app/(app)/projects/[projectId]/cms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/projects/[projectId]/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/dashboard">> = Specific
  const handler = {} as typeof import("../../../app/(app)/projects/[projectId]/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/projects/[projectId]/forms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/forms">> = Specific
  const handler = {} as typeof import("../../../app/(app)/projects/[projectId]/forms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/projects/[projectId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]">> = Specific
  const handler = {} as typeof import("../../../app/(app)/projects/[projectId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/projects/[projectId]/pages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/pages">> = Specific
  const handler = {} as typeof import("../../../app/(app)/projects/[projectId]/pages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/projects/[projectId]/settings/domains/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/settings/domains">> = Specific
  const handler = {} as typeof import("../../../app/(app)/projects/[projectId]/settings/domains/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/projects/[projectId]/settings/general/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/settings/general">> = Specific
  const handler = {} as typeof import("../../../app/(app)/projects/[projectId]/settings/general/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/projects/[projectId]/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/settings">> = Specific
  const handler = {} as typeof import("../../../app/(app)/projects/[projectId]/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/projects/[projectId]/settings/redirects/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/settings/redirects">> = Specific
  const handler = {} as typeof import("../../../app/(app)/projects/[projectId]/settings/redirects/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/projects/[projectId]/settings/staging/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/settings/staging">> = Specific
  const handler = {} as typeof import("../../../app/(app)/projects/[projectId]/settings/staging/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/projects/[projectId]/settings/tracking/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/settings/tracking">> = Specific
  const handler = {} as typeof import("../../../app/(app)/projects/[projectId]/settings/tracking/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/projects/[projectId]/settings/versions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/settings/versions">> = Specific
  const handler = {} as typeof import("../../../app/(app)/projects/[projectId]/settings/versions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/projects/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects">> = Specific
  const handler = {} as typeof import("../../../app/(app)/projects/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(auth)/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../app/(auth)/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(editor)/projects/[projectId]/pages/[pageId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/pages/[pageId]">> = Specific
  const handler = {} as typeof import("../../../app/(editor)/projects/[projectId]/pages/[pageId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/ai/cms-schema/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/cms-schema">> = Specific
  const handler = {} as typeof import("../../../app/api/ai/cms-schema/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/ai/edit-section/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/edit-section">> = Specific
  const handler = {} as typeof import("../../../app/api/ai/edit-section/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/ai/generate-page/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/generate-page">> = Specific
  const handler = {} as typeof import("../../../app/api/ai/generate-page/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/ai/seo-fill/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/seo-fill">> = Specific
  const handler = {} as typeof import("../../../app/api/ai/seo-fill/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/export/[format]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/export/[format]">> = Specific
  const handler = {} as typeof import("../../../app/api/export/[format]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/import/design-zip/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/import/design-zip">> = Specific
  const handler = {} as typeof import("../../../app/api/import/design-zip/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/import/framer-url/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/import/framer-url">> = Specific
  const handler = {} as typeof import("../../../app/api/import/framer-url/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/import/webflow-url/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/import/webflow-url">> = Specific
  const handler = {} as typeof import("../../../app/api/import/webflow-url/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../app/(app)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/(app)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/projects/[projectId]/settings/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/projects/[projectId]/settings">> = Specific
  const handler = {} as typeof import("../../../app/(app)/projects/[projectId]/settings/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(editor)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/(editor)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
